### ISSUE TITLE
Inquiry About Negative ‘amount’ Values in API Output

### ISSUE THREAD

**Issue by tksarah** [AstarNetwork/astar-token-api#160] opened 2024-07-13 14:55 UTC
I have a question.

When using the following API, I’ve recently noticed addresses with a negative amount. What does this mean?

`https://api.astar.network/api/v3/astar/dapps-staking/stakerslist/[contractAddress]`

**sample output:**
```
  {
    "stakerAddress": "beCWnssJmDmSzRCsj1FR4LfocPx6zZwa8Br3CGsPAcLj4h5",
    "amount": "-60000000000000000000000"
  },
  {
    "stakerAddress": "WDTjELRL7B3pX5ZwYn1bxwxUQ4sX7vv3DFHoPpuUkKKwChE",
    "amount": "-555000000000000000000"
  },
```

Until now, I have been summing up the "amount" of stakers from this API to calculate the current total staking amount for dApp. However, I have come across dApps that end up with a negative total staking amount due to the inclusion of negative numbers. Therefore, I think it is necessary to correctly understand the meaning of these negative numbers.

Alternatively, if it is some sort of bug, I would appreciate it if it could be fixed.

**Comment by bobo-k2** [comment] 2024-07-16 08:32
HI @tksarah thank you for the ticket. Negative numbers usually means unstake. Sum of all stakes/unstakes should be >=0. If you are getting a negative sum this must be a bug which become visible after dApp staking period 2 started.
I will check that.

Please share the address which gives you negative numbers.

**Comment by tksarah** [comment] 2024-07-16 22:25
Thank you for your reply. @bobo-k2 
From what I've seen of the data, my guess as to what "negative values" mean was the same as yours. Therefore, I was able to understand that part.

On the other hand, I am using this API to create a system that can aggregate data, but since yesterday's aggregation, addresses that take negative values when summed up have suddenly disappeared. Therefore, at this point, I do not have any addresses to share where this phenomenon is occurring.
However, I don't know if this phenomenon is related, but the address "0x74cc66cd0cf57bb2a0f237c89bcf8db92d3721a8", which has already been removed from the list, is still a negative value. (This was "0" a little while ago. Since it's delisted, it makes sense that it remains "0".)

Also, I may need to write this to the astar-apps side, but I noticed something new yesterday from a related perspective. The amount of staking by the staker in the values obtained with this API (/api/v3/{network}/dapps-staking/stakerslist/{contractAddress}) is different from the amount of staking displayed on the Astar Portal. (I will refrain from writing this because it is my address)
(For example, while Astar Portal displays 5500, the data obtained from the API is 6000. The difference is not significant, but there is enough of a gap to notice the discrepancy immediately.)

**Comment by bobo-k2** [comment] 2024-07-18 07:45
Hi @tksarah please check now. This should be fixed.

**Comment by tksarah** [comment] 2024-07-18 09:59
Hi @bobo-k2 

Thank you so much!
That's wonderful!
All the gaps I was checking have been improved.

By the way, what was the cause?
Is the following content related? 
* https://github.com/AstarNetwork/astar-token-api/pull/161#event-13551136244

I will also let you know about the page I created.
https://agent.sun-t-sarah.work/
Currently, I believe you can check the correct values here.

**Comment by bobo-k2** [comment] 2024-07-18 10:34
Hi @tksarah the root cause is fixed in https://github.com/AstarNetwork/dapps-staking-indexer-v3/pull/26 As I suspected above the issue was cause by incorrect handling of dApp staking periods.
Token API PR you mentioned https://github.com/AstarNetwork/astar-token-api/pull/161#event-13551136244 is just to support new indexer data structure 

I will bookmark your page. It looks nice and useful. If 
Thank you for your contribution and if you find any other inconsistency in Token API data don't hesitate to create an issue.

**Comment by tksarah** [comment] 2024-07-18 10:48
Thank you! I understood.

**Comment by tksarah** [comment] 2024-07-18 10:50
This issue has been resolved.

**Closed as completed** 2024-07-18 10:49 UTC
Labels: bug
